---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv
  namespace: blockchain
  labels:
    type: local
    name: sharedvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dev/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  namespace: blockchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: sharedvolume
