apiVersion: v1
kind: Service
metadata:
  name: blockchain-explorer-db
  namespace: blockchain
  labels:
    run: explorer-db
spec:
  type: ClusterIP 
  selector:
    name: explorer-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432 
    name: pgsql
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-explorer-app
  namespace: blockchain
  labels:
    run: explorer-app
spec:
  type: LoadBalancer 
  selector:
    name: explorer-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-explorer-db
  namespace: blockchain
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: explorer-db
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc

      containers:
      - name: postgres
        image: postgres:10.4-alpine
        env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: DATABASE_DATABASE
          value: fabricexplorer
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /shared/
          name: sharedvolume
      nodeSelector:
        kops.k8s.io/instancegroup: blockchain-nodes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-explorer-app
  namespace: blockchain
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: explorer-app
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc

      containers:
      - name: explorer-app
        image: hyperledger/explorer:latest
        command: ["sh", "-c", "mkdir -p /opt/explorer/app/platform/fabric/; mkdir -p /tmp/; mv /opt/explorer/app/platform/fabric/config.json /opt/explorer/app/platform/fabric/config.json.vanilla; cp /shared/artifacts/explorer/config.json /opt/explorer/app/platform/fabric/config.json; cd /opt/explorer; node $EXPLORER_APP_PATH/main.js && tail -f /dev/null;"]
        env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - name: sharedvolume
          mountPath: /shared
      nodeSelector:
        kops.k8s.io/instancegroup: blockchain-nodes